blank_issues_enabled: true
contact_links:
  - name: A security problem
    url: https://github.com/sultanovazamat/bilby/security/advisories/new
    about: Report a vulnerability privately to the maintainer.
